apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: nirmata-kyverno-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
  name: kyverno-pod-deleter
rules:
- apiGroups: [""] # Core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "delete"] # Ensure 'update' is included for mutation

