apiVersion: kyverno.io/v2beta1
kind: ClusterCleanupPolicy
metadata:
  name: cleanup-deployments
  annotations:
    policies.kyverno.io/description: "A deployment that has an `sre.corp.org/troubleshooting-needed` annotation indicates there is some issue with the deployment that needs further troubleshooting. As such deployments with 0 replicas and this annotation must be cleaned up. This policy finds and deletes all deployments that have `sre.corp.org/troubleshooting-needed` annotation in them and helps with resource optimization. "
spec:
  match:
    any:
    - resources:
        annotations:
          sre.corp.org/troubleshooting-needed: "true"
        kinds:
        - Deployment
  schedule: "* * * * *"

