apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno 
    app.kubernetes.io/part-of: kyverno
  name: kyverno-deployment-deleter
rules:
- apiGroups: ["apps"] # Core API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "delete"] # Ensure 'update' is included for mutation

