apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-impersonate-group-role
  annotations:
    policies.kyverno.io/title: Check for ServiceAccounts with non compliant Roles/ClusterRoles which allow impersonating a group.
    policies.kyverno.io/category: RBAC
    policies.kyverno.io/severity: critical
    policies.kyverno.io/minversion: 1.12.0
    kyverno.io/kyverno-version: 1.12.0
    kyverno.io/kubernetes-version: "1.28"
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-
      This policy will check for all the service accounts which are mapped with the Roles/ClusterRoles allowing impersonating a groups.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-impersonate-group-clusterrole
      match:
        any:
        - resources:
            kinds:
            - ClusterRoleBinding
      context:
        - name: role
          apiCall:
            urlPath: "/apis/rbac.authorization.k8s.io/v1/clusterroles/{{ request.object.roleRef.name }}"
      validate:
        message: >- 
           ClusterRoleBinding {{ request.object.metadata.name }} with subjects {{ request.object.subjects[].name }}
           is using role {{role.metadata.name}}
        deny:
          conditions:
            any:
              - key: "{{ contains(role.rules[].verbs[], 'impersonate') && contains(role.rules[].resources[], 'groups') }}"
                operator: Equals
                value: true
