apiVersion: kyverno.io/v2beta1
kind: ClusterCleanupPolicy
metadata:
  name: clean-stale-namespaces
spec:
  match:
    any:
    - resources:
        annotations:
          allow-delete: "true"
        kinds:
        - Namespace
  schedule: "* * * * *"

