apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-serviceaccount-any-operation-role
  annotations:
    policies.kyverno.io/title: Check for ServiceAccounts with non compliant Roles/ClusterRoles which allow operation on any resource.
    policies.kyverno.io/category: RBAC
    policies.kyverno.io/severity: critical
    policies.kyverno.io/minversion: 1.12.0
    kyverno.io/kyverno-version: 1.12.0
    kyverno.io/kubernetes-version: "1.28"
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-
      This policy will check for all the service accounts which are mapped with the wildcard resource and apiGroup for given verb 
      (delete, deletecollection, create, list, get, impersonate) 
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-wildcard-resources-apigroups-role
      match:
        any:
        - resources:
            kinds:
            - RoleBinding
      preconditions:
        any:
        - key: "{{ request.object.roleRef.kind || 'ClusterRole' }}"
          operator: NotEquals
          value: ClusterRole
      context:
        - name: role
          apiCall:
            urlPath: "/apis/rbac.authorization.k8s.io/v1/namespaces/{{ request.object.metadata.namespace }}/roles/{{ request.object.roleRef.name }}"
      validate:
        message: >- 
           RoleBinding {{ request.object.metadata.name }} with subjects {{ request.object.subjects[].name }}
           is using role {{role.metadata.name}}
        deny:
          conditions:
            any:
              - key: "{{ (contains(role.rules[].verbs[], 'delete') || contains(role.rules[].verbs[], 'deletecollection') || contains(role.rules[].verbs[], 'create') || contains(role.rules[].verbs[], 'list') || contains(role.rules[].verbs[], 'get') || contains(role.rules[].verbs[], 'impersonate') ) && contains(role.rules[].resources[], '*') && contains(role.rules[].apiGroups[], '*') }}"
                operator: Equals
                value: true
