apiVersion: kyverno.io/v2beta1
kind: ClusterCleanupPolicy
metadata:
  name: clean-stale-deployments
spec:
  match:
    any:
    - resources:
        annotations:
          allow-delete: "true"
        kinds:
        - Service
  schedule: "* * * * *"

