apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mark-bare-pods-cleanup
  annotations:
    policies.kyverno.io/title: Mark Bare Pods for Cleanup
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.1
    policies.kyverno.io/minversion: 1.10.0
    pod-policies.kyverno.io/autogen-controllers: none
    kyverno.io/kubernetes-version: "1.27"
    policies.kyverno.io/description: "A bare Pod is any Pod created directly and not owned by a controller such as a Deployment or Job. Bare Pods are often create manually by users in an attempt to troubleshoot an issue. If left in the cluster, they create clutter, increase cost, and can be a security risk. Bare Pods can be marked for cleanup and later cleaned up using cleanup policies. This policy finds all such pods and adds an appropriate annotation for later cleanup\"      "
spec:
  #mutateExistingOnPolicyUpdate: true
  rules:
  - name: mark-bare-pods-cleanup
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - kyverno-test
    mutate:
      targets:
      - apiVersion: v1
        kind: Pod
        namespace: "{{request.namespace}}"
        preconditions:
          all:
          - key: "{{target.metadata.ownerReferences[] || `[]` }}"
            operator: Equals
            value: []
          - key: "{{target.metadata.annotations.\"allow-delete\"  || 'empty' }}"
            operator: NotEquals
            value: "true"
      patchStrategicMerge:
        metadata:
          annotations:
            allow-delete: "true"

