---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-vpa
  annotations:
    policies.kyverno.io/title: Resource Usage
    policies.kyverno.io/category: Resource Optimization
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      The policy checks for the target utilisation and scale the pods based on the HPA values. This policy,
      requiring Kubernetes v1.19 or later.
spec:
  generateExisting: true
  rules:
    - name: create-for-podcontrollers
      match:
        any:
        - resources:
            kinds:
              - Deployment      
              - StatefulSet
      generate:
        synchronize: true
        kind: VerticalPodAutoscaler
        apiVersion: autoscaling.k8s.io/v1
        name: "{{request.object.metadata.name}}-kyverno" 
        namespace: "{{request.object.metadata.namespace}}"
        data:
          spec:
            targetRef:
              apiVersion: "{{request.object.apiVersion}}"
              kind: "{{request.object.kind}}"
              name: "{{request.object.metadata.name}}"
            updatePolicy:
              updateMode: "Off" 
