apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cleanup-controller
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
rules:
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - delete
      - get
      - list
      - watch

