apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-cleanup-controller-binding
subjects:
  - kind: ServiceAccount
    name: kyverno-cleanup-controller
    namespace: kyverno # Replace with the namespace where Kyverno is installed
roleRef:
  kind: ClusterRole
  name: kyverno-cleanup-controller
  apiGroup: rbac.authorization.k8s.io

