#The described logic currently deletes the ReplicaSets created 30 seconds ago. You can adjust this timeframe according to your specific requirements.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mark-empty-replicasets-cleanup
spec:
  mutateExistingOnPolicyUpdate: true
  rules: 
  - name: mark-empty-replicasets-cleanup
    match:
      any:
      - resources:
          kinds:
            - ReplicaSet
    exclude:
      any:
      - resources:
          namespaces:
            - kube-system
    mutate:
      targets:
      - apiVersion: apps/v1
        kind: ReplicaSet
        namespace: "{{request.namespace}}"
        context: 
        - name: objName
          variable: 
            jmesPath: "target.metadata.creationTimestamp"
        preconditions:
          all:
          - key: "{{ target.spec.replicas }}"
            operator: Equals
            value: 0
          - key: "{{ time_diff('{{objName}}','{{ time_now_utc() }}') }}"
            operator: GreaterThan
            value: "0h60m0s"
      patchStrategicMerge:
        metadata:
          annotations:
            allow-delete: "true"

